version: "3.3"

networks:
  es-net:
    driver: bridge

services:

  mbtastreamingclient:
    container_name: mbtastreamingclient
    image: barrymullan/mbtastreamingclient:latest
    networks:
    - es-net

  mbtakafkaconsumer:
    container_name: mbtakafkaconsumer
    hostname: mbtakafkaconsumer
    image: barrymullan/mbtakafkaconsumer:latest
    ports:
      - 8080:8080

    networks:
    - es-net

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.1.0
    networks:
    - es-net
    volumes:
      - $PWD/final-project/volumes/filebeat/data:/usr/share/filebeat/data
      # - $PWD/final-project/volumes/filebeat:/usr/share/filebeat
      - $PWD/final-project/volumes/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - ELASTICSEARCH_HOST=es-container

  redis:
    container_name: redis
    hostname: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - es-net
    volumes:
      - $PWD/final-project/volumes/redis:/bitnami/redis/data
    ports:
      - 6379:6379

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    container_name: zookeeper
    volumes:
      - $PWD/final-project/volumes/zk-data:/var/lib/zookeeper/data
      - $PWD/final-project/volumes/zk-txn-log:/var/lib/zookeeper/log
    networks:
      - es-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  #Kafka container node1
  broker1:
    image: confluentinc/cp-server:6.2.1
    hostname: broker1
    container_name: broker1
    healthcheck:
      test: nc -z localhost 9092
    volumes:
    - $PWD/final-project/volumes/broker1/data:/var/lib/kafka/data
    networks:
      - es-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

